// Unifies one-time tasks and (merged) recurring occurrences into one list the
// Tasks / Dashboard / Calendar screens can render and toggle.
import { occurrencesForWindow } from "../../lib/recurrence";
import type { Occurrence, Priority, Recurrence, Status, Task } from "../../lib/types";

export interface AgendaItem {
  key: string;
  title: string;
  notes: string;
  category: string;
  priority: Priority;
  assignee: string;
  date: string; // due/occurrence date ("" for undated one-time)
  status: Status;
  done: boolean;
  recurring: boolean;
  taskId?: string;
  occurrence?: Occurrence;
}

export function buildAgenda(
  tasks: Task[],
  recurrences: Recurrence[],
  windowStart: string,
  windowEnd: string
): AgendaItem[] {
  const items: AgendaItem[] = [];

  // One-time tasks (never generated by the recurrence engine).
  for (const t of tasks) {
    if (t.recurrenceId) continue;
    items.push({
      key: t.id,
      title: t.title,
      notes: t.notes,
      category: t.category,
      priority: t.priority,
      assignee: t.assignee,
      date: t.dueDate,
      status: t.status,
      done: t.status === "Completed",
      recurring: false,
      taskId: t.id,
    });
  }

  // Recurring occurrences (virtual + materialized overrides).
  const occ: Occurrence[] = occurrencesForWindow(
    recurrences,
    tasks,
    windowStart,
    windowEnd
  );
  for (const o of occ) {
    items.push({
      key: o.key,
      title: o.title,
      notes: "",
      category: o.category,
      priority: o.priority,
      assignee: o.assignee,
      date: o.date,
      status: o.status,
      done: o.status === "Completed",
      recurring: true,
      taskId: o.taskId,
      occurrence: o,
    });
  }

  return items;
}

const PRI_RANK: Record<Priority, number> = {
  VeryHigh: 0,
  High: 1,
  Medium: 2,
  Low: 3,
  VeryLow: 4,
};

/** Count of not-yet-done items (one-off tasks + recurring occurrences) due on `date`. */
export function dueCountOn(tasks: Task[], recurrences: Recurrence[], date: string): number {
  return buildAgenda(tasks, recurrences, date, date).filter(
    (i) => i.date === date && !i.done
  ).length;
}

export function sortAgenda(items: AgendaItem[]): AgendaItem[] {
  return [...items].sort((a, b) => {
    if (a.done !== b.done) return a.done ? 1 : -1;
    if (a.date && b.date && a.date !== b.date) return a.date < b.date ? -1 : 1;
    if (a.date && !b.date) return -1;
    if (!a.date && b.date) return 1;
    return PRI_RANK[a.priority] - PRI_RANK[b.priority];
  });
}
